services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: pip install -r cdccTool/requirements.txt
    startCommand: gunicorn cdccTool.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0